-- All census data is joined 

{{
    configs(
        unique_key='id', 
        alias='census',
        materialized='table',
        post_hook=[ 
            "ALTER TABLE {{ this }} ADD PRIMARY KEY (id)", 
            "ALTER TABLE {{ this }} ADD CONSTRAINT fk_lga_code
            FOREIGN KEY (lga_code) REFERENCES {{ ref('s_LGAs')  }} (code)"
        ]
    )
}}

WITH central_tendencies AS(
    SELECT * FROM {{ ref('b_central_tendencies') }}
),

personal_characteristics AS (
    SELECT * FROM {{ ref('b_personal_characteristics') }}
), 

-- this last CTE allows a new key to be generated by the final SELECT below it 
merged AS(
    SELECT 
    -- strip out characters and cast to INT 
        REGEXP_REPLACE(lga_code_2016, '[A-Za-z]', '', 'g')::INT as lga_code, 
    -- indicate the temporal source of the data with the actual 2016 census date 
        "2016-08-09"::DATE as census_date, 
        * 
    FROM central_tendencies 
    INNER JOIN personal_characteristics 
    ON central_tendencies.lga_code_2016 = personal_characteristics.lga_code_2016
) 

SELECT 
    {{ dbt_utils.generate_surrogate_key(['lga_code', 'census_date']) }} as id, -- new unique identifier will allow ingestion of later census data also 
    lga_code, 
    census_date, 
    -- Casting G01 fields 

    -- Age categories 
	Tot_P_M::INT AS total_males, 
	Tot_P_F::INT AS total_females, 
	Tot_P_P::INT AS total_persons, 
	Age_0_4_yr_M::INT AS males_under_4, 
	Age_0_4_yr_F::INT AS females_under_4,
	Age_0_4_yr_P::INT AS persons_under_4,
	Age_5_14_yr_M::INT AS males_5_14,
	Age_5_14_yr_F::INT AS females_5_14, 
	Age_5_14_yr_P::INT AS persons_5_14, 
	Age_15_19_yr_M::INT AS males_15_19, 
	Age_15_19_yr_F::INT AS females_15_19, 
	Age_15_19_yr_P::INT AS persons_15_19,
	Age_20_24_yr_M::INT AS males_20_24,
	Age_20_24_yr_F::INT AS females_20_24,
	Age_20_24_yr_P::INT AS persons_20_24,
	Age_25_34_yr_M::INT AS males_25_34,
	Age_25_34_yr_F::INT AS females_25_34,
	Age_25_34_yr_P::INT AS persons_25_34,
	Age_35_44_yr_M::INT AS males_35_44, 
	Age_35_44_yr_F::INT AS females_35_44, 
	Age_35_44_yr_P::INT AS persons_35_44,
	Age_45_54_yr_M::INT AS males_45_54,
	Age_45_54_yr_F::INT AS females_45_54, 
	Age_45_54_yr_P::INT AS persons_45_54,
	Age_55_64_yr_M::INT AS males_55_64,
	Age_55_64_yr_F::INT AS females_55_64,
	Age_55_64_yr_P::INT AS persons_55_64,
	Age_65_74_yr_M::INT AS males_65_74,
	Age_65_74_yr_F::INT AS females_65_74,
	Age_65_74_yr_P::INT AS persons_65_74,
	Age_75_84_yr_M::INT AS males_75_84,
	Age_75_84_yr_F::INT AS females_75_84,
	Age_75_84_yr_P::INT AS persons_75_84,
	Age_85ov_M::INT AS males_over_85,
	Age_85ov_F::INT AS females_over_85,
	Age_85ov_P::INT AS persons_over_85,

 -- Census Night Location
    Counted_Census_Night_home_M::INT AS counted_home_males,
    Counted_Census_Night_home_F::INT AS counted_home_females,
    Counted_Census_Night_home_P::INT AS counted_home_persons,
    Count_Census_Nt_Ewhere_Aust_M::INT AS counted_elsewhere_males,
    Count_Census_Nt_Ewhere_Aust_F::INT AS counted_elsewhere_females,
    Count_Census_Nt_Ewhere_Aust_P::INT AS counted_elsewhere_persons,
    
    -- Indigenous Status
    Indigenous_psns_Aboriginal_M::INT AS indigenous_aboriginal_males,
    Indigenous_psns_Aboriginal_F::INT AS indigenous_aboriginal_females,
    Indigenous_psns_Aboriginal_P::INT AS indigenous_aboriginal_persons,
    Indig_psns_Torres_Strait_Is_M::INT AS indigenous_torres_strait_males,
    Indig_psns_Torres_Strait_Is_F::INT AS indigenous_torres_strait_females,
    Indig_psns_Torres_Strait_Is_P::INT AS indigenous_torres_strait_persons,
    Indig_Bth_Abor_Torres_St_Is_M::INT AS indigenous_both_males,
    Indig_Bth_Abor_Torres_St_Is_F::INT AS indigenous_both_females,
    Indig_Bth_Abor_Torres_St_Is_P::INT AS indigenous_both_persons,
    Indigenous_P_Tot_M::INT AS indigenous_total_males,
    Indigenous_P_Tot_F::INT AS indigenous_total_females,
    Indigenous_P_Tot_P::INT AS indigenous_total_persons,
    
    -- Birthplace
    Birthplace_Australia_M::INT AS birthplace_australia_males,
    Birthplace_Australia_F::INT AS birthplace_australia_females,
    Birthplace_Australia_P::INT AS birthplace_australia_persons,
    Birthplace_Elsewhere_M::INT AS birthplace_elsewhere_males,
    Birthplace_Elsewhere_F::INT AS birthplace_elsewhere_females,
    Birthplace_Elsewhere_P::INT AS birthplace_elsewhere_persons,
    
    -- Language Spoken at Home
    Lang_spoken_home_Eng_only_M::INT AS language_english_only_males,
    Lang_spoken_home_Eng_only_F::INT AS language_english_only_females,
    Lang_spoken_home_Eng_only_P::INT AS language_english_only_persons, 
    Lang_spoken_home_Oth_Lang_M::INT AS language_other_males,
    Lang_spoken_home_Oth_Lang_F::INT AS language_other_females,
    Lang_spoken_home_Oth_Lang_P::INT AS language_other_persons,
    
    -- Citizenship
    Australian_citizen_M::INT AS citizen_males,
    Australian_citizen_F::INT AS citizen_females,
    Australian_citizen_P::INT AS citizen_persons,
    
    -- Educational Attendance (Age Groups)
    Age_psns_att_educ_inst_0_4_M::INT AS attending_education_males_0_4,
    Age_psns_att_educ_inst_0_4_F::INT AS attending_education_females_0_4,
    Age_psns_att_educ_inst_0_4_P::INT AS attending_education_persons_0_4,
    Age_psns_att_educ_inst_5_14_M::INT AS attending_education_males_5_14,
    Age_psns_att_educ_inst_5_14_F::INT AS attending_education_females_5_14,
    Age_psns_att_educ_inst_5_14_P::INT AS attending_education_persons_5_14,
    Age_psns_att_edu_inst_15_19_M::INT AS attending_education_males_15_19,
    Age_psns_att_edu_inst_15_19_F::INT AS attending_education_females_15_19,
    Age_psns_att_edu_inst_15_19_P::INT AS attending_education_persons_15_19,
    Age_psns_att_edu_inst_20_24_M::INT AS attending_education_males_20_24,
    Age_psns_att_edu_inst_20_24_F::INT AS attending_education_females_20_24,
    Age_psns_att_edu_inst_20_24_P::INT AS attending_education_persons_20_24,
    Age_psns_att_edu_inst_25_ov_M::INT AS attending_education_males_over_25, 
    Age_psns_att_edu_inst_25_ov_F::INT AS attending_education_females_over_25,
    Age_psns_att_edu_inst_25_ov_P::INT AS attending_education_persons_over_25,
    
    -- Highest Year of School Completed
    High_yr_schl_comp_Yr_12_eq_M::INT AS highest_year_12_males,
    High_yr_schl_comp_Yr_12_eq_F::INT AS highest_year_12_females,
    High_yr_schl_comp_Yr_12_eq_P::INT AS highest_year_12_persons,
    High_yr_schl_comp_Yr_11_eq_M::INT AS highest_year_11_males,
    High_yr_schl_comp_Yr_11_eq_F::INT AS highest_year_11_females,
    High_yr_schl_comp_Yr_11_eq_P::INT AS highest_year_11_persons,
    High_yr_schl_comp_Yr_10_eq_M::INT AS highest_year_10_males,
    High_yr_schl_comp_Yr_10_eq_F::INT AS highest_year_10_females,
    High_yr_schl_comp_Yr_10_eq_P::INT AS highest_year_10_persons,
    High_yr_schl_comp_Yr_9_eq_M::INT AS highest_year_9_males,
    High_yr_schl_comp_Yr_9_eq_F::INT AS highest_year_9_females,
    High_yr_schl_comp_Yr_9_eq_P::INT AS highest_year_9_persons,
    High_yr_schl_comp_Yr_8_belw_M::INT AS highest_year_8_or_below_males,
    High_yr_schl_comp_Yr_8_belw_F::INT AS highest_year_8_or_below_females,
    High_yr_schl_comp_Yr_8_belw_P::INT AS highest_year_8_or_below_persons,
    High_yr_schl_comp_D_n_g_sch_M::INT AS highest_did_not_go_school_males,
    High_yr_schl_comp_D_n_g_sch_F::INT AS highest_did_not_go_school_females,
    High_yr_schl_comp_D_n_g_sch_P::INT AS highest_did_not_go_school_persons,
    
    -- Dwelling Counts
    Count_psns_occ_priv_dwgs_M::INT AS occupants_private_dwelling_males,
    Count_psns_occ_priv_dwgs_F::INT AS occupants_private_dwelling_females,
    Count_psns_occ_priv_dwgs_P::INT AS occupants_private_dwelling_persons,
    Count_Persons_other_dwgs_M::INT AS occupants_other_dwelling_males,
    Count_Persons_other_dwgs_F::INT AS occupants_other_dwelling_females,
    Count_Persons_other_dwgs_P::INT AS occupants_other_dwelling_persons
    
    -- Casting G02 fields 

    -- Note on datatypes: 
        -- Values appear to be INT, but could conceptually be decimal, so NUMERIC is used for flexibility in case census reporting practices change
    Median_age_persons::NUMERIC AS median_age_persons, 
    Median_mortage_repay_monthly::NUMERIC AS median_mortgage_repay_monthly,
    Median_tot_prsnl_inc_weekly::NUMERIC AS median_total_personal_income_weekly,
    Median_rent_weekly::NUMERIC AS median_rent_weekly, 
    Median_tot_fam_inc_weekly::NUMERIC AS median_total_family_income_weekly, 
    Average_num_psns_per_bedroom::DECIMAL(2,1) AS average_number_persons_per_bedroom, 
    Median_tot_hhd_inc_weekly::NUMERIC AS median_total_household_income_weekly, 
    Average_household_size::DECIMAL(2,1) AS average_household_size 

FROM merged 

